### PR TITLE
fix(generic): fix flawed logic

### PR DESCRIPTION
**Pull request by cueedee**
Mea culpa, I goofed up my logic on the previous change.

### CODE REVIEW

**Comment by Qwerios** [comment]
Well there goes my blind faith in your work David ;)

Version 0.1.21 has been published

**Comment by cueedee** [comment]
Yup, as you should. Faith is good but avid suspicion is better.

**Comment by cueedee** [comment]
Also note that I forgot to commit the `grunt` build result as well this time. Would you like another pull request for that?

It surprised me a bit to find out that build results are under version control too. Shouldn't `/lib/` be in your `.gitignore`?

**Comment by Qwerios** [comment]
I've already built the lib file. It's part of my prepublish script in package.json so its never forgotten.

The reason this happens is because people consume the JavaScript version and not the CoffeeScript version of the files. I can take the lib files out of git but for local development purposes it is sometimes easier this way.

So in short: nu pull request needed. All is fine

**Comment by cueedee** [comment]
ack

**Pull request merged**
